run:
  timeout: 5m

linters-settings:
  goimports:
    local-prefixes: github.com/web-seven/overlock

  gosec:
    includes:
      - G401
      - G403
      - G404

  revive:
    rules:
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: errorf
      - name: indent-error-flow

linters:
  disable-all: true
  enable:
    - errorlint
    - gosec
    - govet
    - ineffassign
    - revive
    - unparam
    - goimports

issues:
  exclude-use-default: false
  exclude-dirs:
    - .git
    - vendor
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_gen\\.go$"

  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - unparam

    - text: "result 0 \\(error\\) is always nil"
      linters:
        - unparam

  max-issues-per-linter: 100
  max-same-issues: 50
